<?= $this->include('Pendidikan/Institusi/layout/header') ?>
<?= $this->include('Pendidikan/Institusi/layout/sidebar') ?>

<div class="row"><div class="col-12 mb-4"><div class="d-flex align-items-center justify-content-between"><div><h4 class="fw-bold">Edit Pengajuan Mahasiswa</h4><p class="text-muted mb-0">Perbarui data pengajuan dan mahasiswa, lalu unggah dokumen pengganti bila diperlukan.</p></div><a href="<?= base_url('pendidikan/institusi/pengajuan/status') ?>" class="btn btn-outline-secondary"><i class="fas fa-list me-1"></i> Daftar Pengajuan</a></div></div></div>
<?php if (!empty($pengajuan['catatan'])) : ?><div class="card border-warning bg-light-warning mb-4"><div class="card-body"><h6 class="fw-bold text-warning"><i class="fas fa-exclamation-triangle me-2"></i>Catatan Revisi Admin:</h6><p class="mb-0"><?= esc($pengajuan['catatan']) ?></p></div></div><?php endif; ?>

<form id="formPengajuanMahasiswa" action="<?= base_url('pendidikan/institusi/pengajuan/update/' . $pengajuan['id']) ?>" method="POST" enctype="multipart/form-data" novalidate>
<div class="row">
<div class="col-12"><div class="card shadow-sm border-0 mb-4"><div class="card-header bg-light py-3 border-0"><h6 class="mb-0 fw-bold text-danger"><i class="fas fa-info-circle me-2"></i>Data Pengajuan</h6></div><div class="card-body">
<div class="row mb-3"><div class="col-md-6"><label class="form-label small fw-bold">Nama Institusi</label><input class="form-control" value="<?= esc($pengajuan['institusi']) ?>" readonly></div><div class="col-md-6"><label class="form-label small fw-bold">Jenis Program</label><select class="form-select" name="jenis_program" required><option value="" disabled>Pilih Program...</option><?php foreach (['Akademik','Spesialis (Residen)','Profesi (D1)','Koas','Magang'] as $v): ?><option value="<?= $v ?>" <?= $pengajuan['jenis_program'] === $v ? 'selected' : '' ?>><?= $v ?></option><?php endforeach; ?></select></div></div>
<div class="row mb-3"><div class="col-md-3"><label class="form-label small fw-bold">Profesi</label><select class="form-select" name="profesi_id" required><option value="" disabled>Pilih Profesi...</option><?php foreach ($list_profesi as $p): ?><option value="<?= $p['id_profesi'] ?>" <?= (string)$pengajuan['id_profesi'] === (string)$p['id_profesi'] ? 'selected' : '' ?>><?= esc($p['nama_profesi']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label small fw-bold">Program Studi</label><input class="form-control" name="prodi_asal" value="<?= esc($pengajuan['prodi']) ?>" required></div><div class="col-md-3"><label class="form-label small fw-bold">Tanggal Mulai</label><input type="date" class="form-control" name="tgl_mulai" value="<?= esc($pengajuan['tgl_mulai']) ?>" required></div><div class="col-md-3"><label class="form-label small fw-bold">Tanggal Selesai</label><input type="date" class="form-control" name="tgl_selesai" value="<?= esc($pengajuan['tgl_selesai']) ?>" required></div></div>
<div class="row"><div class="col-md-6"><label class="form-label">Nama Penanggung Jawab</label><input class="form-control" name="nama_pj" value="<?= esc($pengajuan['penanggung_jawab']) ?>" required></div><div class="col-md-6"><label class="form-label">Nomor HP Penanggung Jawab</label><input class="form-control" name="hp_pj" value="<?= esc($pengajuan['hp_pj']) ?>" required></div></div>
</div></div></div>

<div class="col-12"><div class="card shadow-sm border-0 mb-4"><div class="card-header bg-light py-3 border-0 d-flex flex-wrap justify-content-between align-items-center gap-2"><h6 class="mb-0 fw-bold text-danger"><i class="fas fa-users me-2"></i>Data Mahasiswa</h6><button type="button" class="btn btn-sm btn-danger shadow-sm" id="btnAddMahasiswa"><i class="fas fa-plus me-1"></i> Tambah Mahasiswa</button></div><div class="card-body" id="mahasiswaList">
<?php foreach ($pengajuan['mahasiswa'] as $i => $m): $n=$i+1; ?><div class="student-row border rounded p-3 mb-3"><div class="d-flex justify-content-between align-items-center mb-3"><span class="fw-bold">Mahasiswa <span class="student-number"><?= $n ?></span></span><button type="button" class="btn btn-sm btn-light text-danger btn-remove-mhs"><i class="fas fa-trash"></i></button></div><div class="row g-3">
<div class="col-12 col-md-6 col-xl-4"><label class="form-label small fw-bold">Nama Lengkap *</label><input class="form-control" name="mhs_nama[]" value="<?= esc($m['nama']) ?>" required></div><div class="col-12 col-md-6 col-xl-4"><label class="form-label small fw-bold">NIM *</label><input class="form-control" name="mhs_nim[]" value="<?= esc($m['nim']) ?>" required></div><div class="col-12 col-md-6 col-xl-4"><label class="form-label small fw-bold">Tanggal Lahir *</label><input type="date" class="form-control" name="mhs_tgl_lahir[]" value="<?= esc($m['dob']) ?>" required></div><div class="col-12 col-md-6 col-xl-4"><label class="form-label small fw-bold">Jenis Kelamin *</label><select class="form-select" name="mhs_jk[]"><option value="L" <?= $m['jk']==='L'?'selected':'' ?>>Laki-laki</option><option value="P" <?= $m['jk']==='P'?'selected':'' ?>>Perempuan</option></select></div><div class="col-12 col-md-6 col-xl-4"><label class="form-label small fw-bold">Semester</label><input type="number" class="form-control" name="mhs_semester[]" value="<?= esc($m['semester']) ?>" min="1" max="20"></div><div class="col-12 col-md-6 col-xl-4"><label class="form-label small fw-bold">No. Handphone</label><input class="form-control" name="mhs_hp[]" value="<?= esc($m['hp']) ?>"></div><div class="col-12"><label class="form-label small fw-bold">Email *</label><input type="email" class="form-control" name="mhs_email[]" value="<?= esc($m['email']) ?>" required></div>
<div class="col-12 col-lg-4"><label class="form-label small fw-bold">Pas Foto</label><input type="file" class="form-control" name="mhs_foto_<?= $n ?>" accept=".jpg,.jpeg,.png"><small class="text-muted">JPG/PNG, Maks 2MB</small></div><div class="col-12 col-lg-4"><label class="form-label small fw-bold">Ijazah Terakhir</label><input type="file" class="form-control" name="mhs_ijazah_<?= $n ?>" accept=".pdf"><small class="text-muted">PDF, Maks 2MB</small></div><div class="col-12 col-lg-4"><label class="form-label small fw-bold">Surat Ket. Aktif</label><input type="file" class="form-control" name="mhs_sk_<?= $n ?>" accept=".pdf"><small class="text-muted">PDF, Maks 2MB</small></div>
</div></div><?php endforeach; ?>
</div></div></div>

<div class="col-12"><div class="card shadow-sm border-0 mb-4"><div class="card-header bg-light py-3 border-0"><h6 class="mb-0 fw-bold text-danger"><i class="fas fa-file-upload me-2"></i>Dokumen Pendukung</h6></div><div class="card-body"><p class="text-muted small mb-3">Ukuran maksimal setiap berkas: 2 MB. Kosongkan bila tidak ingin mengganti berkas saat ini.</p><div class="row g-3">
<?php $docs=[['doc_proposal','1. Proposal (PDF)','file_proposal','.pdf'],['doc_pengantar','2. Surat Pengantar (PDF)','file_surat_pengantar','.pdf'],['doc_logbook','3. Log Book (PDF)','file_logbook','.pdf'],['doc_panduan','4. Buku Panduan (PDF)','file_panduan','.pdf'],['doc_daftar_mhs','5. Daftar Nama Mahasiswa (PDF/XLS/XLSX)','file_daftar_mhs','.pdf,.xls,.xlsx'],['doc_kompetensi','6. Surat Level Kompetensi (PDF)','file_kompetensi','.pdf'],['doc_sk_pembimbing','7. SK Pembimbing (PDF)','file_sk_pembimbing','.pdf'],['doc_bukti_bayar','8. Bukti Pembayaran Batch (PDF/JPG/PNG)','file_bukti_bayar','.pdf,.jpg,.jpeg,.png'],['doc_penilaian','9. Dokumen Penilaian (PDF)','file_dokumen_penilaian','.pdf']]; foreach($docs as [$field,$label,$stored,$accept]): ?><div class="col-md-4"><div class="p-3 border rounded bg-light h-100"><label class="form-label small fw-bold"><?= $label ?></label><input type="file" class="form-control form-control-sm" name="<?= $field ?>" accept="<?= $accept ?>"><small class="text-muted d-block mt-1"><?php if(!empty($pengajuan[$stored])): ?><a href="<?= base_url('uploads/dokumen_pengajuan/'.$pengajuan[$stored]) ?>" target="_blank">Lihat file saat ini</a><?php else: ?>Belum ada file<?php endif; ?></small></div></div><?php endforeach; ?>
</div></div></div></div>
<div class="col-12 mb-5"><div class="d-flex justify-content-end gap-2"><a href="<?= base_url('pendidikan/institusi/pengajuan/status') ?>" class="btn btn-light px-4">Batal</a><button type="submit" class="btn btn-danger px-5 fw-bold">UPDATE PENGAJUAN</button></div></div>
</div></form>
<style>.bg-light-warning{background:#fffaf0}</style>
<script>
document.addEventListener('DOMContentLoaded',()=>{
 const f=document.querySelector('#formPengajuanMahasiswa'),l=document.querySelector('#mahasiswaList'),a=document.querySelector('#btnAddMahasiswa'),s=f.querySelector('[type=submit]');let c=l.querySelectorAll('.student-row').length;const max=2097152,m={'.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.pdf':'application/pdf','.xls':'application/vnd.ms-excel','.xlsx':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'};
 const clear=i=>{i.classList.remove('is-invalid');i.parentElement.querySelector('.field-error')?.remove()},label=i=>i.parentElement.querySelector('label')?.textContent.replace('*','').trim()||'Input',show=(i,msg)=>{if(!i)return Swal.fire({icon:'error',title:'Periksa pengajuan',text:msg});clear(i);i.classList.add('is-invalid');const d=document.createElement('div');d.className='invalid-feedback d-block field-error';d.textContent=msg;i.insertAdjacentElement('afterend',d);i.scrollIntoView({behavior:'smooth',block:'center'});i.focus({preventScroll:true})};
 const fileError=i=>{const x=i.files[0];if(!x)return null;const e=x.name.slice(x.name.lastIndexOf('.')).toLowerCase(),z=i.accept.split(',');if(!z.includes(e)||(x.type&&x.type!==m[e]))return label(i)+' harus berformat '+z.map(v=>v.slice(1).toUpperCase()).join('/')+'.';return x.size>max?label(i)+' maksimal 2 MB.':null};
 const valid=i=>{const v=i.value.trim(),n=i.name;if(i.required&&!v)return label(i)+' wajib diisi.';if(i.type==='file')return fileError(i);if(i.validity.typeMismatch||i.validity.badInput)return label(i)+' tidak valid.';if((n==='nama_pj'||n==='mhs_nama[]')&&!/^\p{L}[\p{L}\s.,'-]{1,149}$/u.test(v))return label(i)+' harus berisi 2-150 karakter berupa huruf dan tanda baca nama.';if(n==='prodi_asal'&&v.length>150)return'Program Studi maksimal 150 karakter.';if((n==='hp_pj'||n==='mhs_hp[]')&&v&&!/^[0-9]{8,20}$/.test(v))return label(i)+' harus berisi 8-20 digit angka.';if(n==='mhs_nim[]'&&!/^[A-Za-z0-9.\/-]{3,30}$/.test(v))return label(i)+' harus berisi 3-30 karakter.';if(n==='mhs_semester[]'&&v&&(!Number.isInteger(+v)||+v<1||+v>20))return label(i)+' harus berupa angka 1-20.';if(n==='tgl_selesai'&&v<f.elements.tgl_mulai.value)return'Tanggal selesai tidak boleh lebih awal dari tanggal mulai.';if(n==='mhs_tgl_lahir[]'&&v>=new Date().toISOString().slice(0,10))return label(i)+' harus sebelum hari ini.';return null};
 const row=n=>`<div class="student-row border rounded p-3 mb-3"><div class="d-flex justify-content-between align-items-center mb-3"><span class="fw-bold">Mahasiswa <span class="student-number">${n}</span></span><button type="button" class="btn btn-sm btn-light text-danger btn-remove-mhs"><i class="fas fa-trash"></i></button></div><div class="row g-3"><div class="col-12 col-md-6 col-xl-4"><label class="form-label small fw-bold">Nama Lengkap *</label><input class="form-control" name="mhs_nama[]" required></div><div class="col-12 col-md-6 col-xl-4"><label class="form-label small fw-bold">NIM *</label><input class="form-control" name="mhs_nim[]" required></div><div class="col-12 col-md-6 col-xl-4"><label class="form-label small fw-bold">Tanggal Lahir *</label><input type="date" class="form-control" name="mhs_tgl_lahir[]" required></div><div class="col-12 col-md-6 col-xl-4"><label class="form-label small fw-bold">Jenis Kelamin *</label><select class="form-select" name="mhs_jk[]"><option value="L">Laki-laki</option><option value="P">Perempuan</option></select></div><div class="col-12 col-md-6 col-xl-4"><label class="form-label small fw-bold">Semester</label><input type="number" class="form-control" name="mhs_semester[]" min="1" max="20"></div><div class="col-12 col-md-6 col-xl-4"><label class="form-label small fw-bold">No. Handphone</label><input class="form-control" name="mhs_hp[]"></div><div class="col-12"><label class="form-label small fw-bold">Email *</label><input type="email" class="form-control" name="mhs_email[]" required></div><div class="col-12 col-lg-4"><label class="form-label small fw-bold">Pas Foto *</label><input type="file" class="form-control" name="mhs_foto_${n}" accept=".jpg,.jpeg,.png" required><small class="text-muted">JPG/PNG, Maks 2MB</small></div><div class="col-12 col-lg-4"><label class="form-label small fw-bold">Ijazah Terakhir *</label><input type="file" class="form-control" name="mhs_ijazah_${n}" accept=".pdf" required><small class="text-muted">PDF, Maks 2MB</small></div><div class="col-12 col-lg-4"><label class="form-label small fw-bold">Surat Ket. Aktif *</label><input type="file" class="form-control" name="mhs_sk_${n}" accept=".pdf" required><small class="text-muted">PDF, Maks 2MB</small></div></div></div>`;
 const renumber=()=>{[...l.querySelectorAll('.student-row')].forEach((r,i)=>{let n=i+1;r.querySelector('.student-number').textContent=n;['foto','ijazah','sk'].forEach(x=>r.querySelector('[name^="mhs_'+x+'_"]').name='mhs_'+x+'_'+n)});c=l.querySelectorAll('.student-row').length};
 f.addEventListener('beforeinput',e=>{if((e.target.name==='nama_pj'||e.target.name==='mhs_nama[]')&&e.data&&/^\p{N}+$/u.test(e.data))e.preventDefault()});f.addEventListener('input',e=>{let i=e.target;if(i.name==='nama_pj'||i.name==='mhs_nama[]')i.value=i.value.replace(/\p{N}/gu,'');clear(i)});f.addEventListener('change',e=>{if(!e.target.matches('input,select'))return;clear(e.target);let x=e.target.type==='file'&&fileError(e.target);if(x)show(e.target,x)});
 a.addEventListener('click',()=>{c++;l.insertAdjacentHTML('beforeend',row(c))});l.addEventListener('click',e=>{let b=e.target.closest('.btn-remove-mhs');if(!b)return;Swal.fire({icon:'warning',title:'Hapus mahasiswa?',text:'Data mahasiswa ini akan dikeluarkan dari pengajuan saat perubahan disimpan.',showCancelButton:true,confirmButtonText:'Ya, hapus',cancelButtonText:'Batal',confirmButtonColor:'#c62828'}).then(x=>{if(x.isConfirmed){b.closest('.student-row').remove();renumber()}})});
 f.addEventListener('submit',async e=>{e.preventDefault();for(const i of f.querySelectorAll('input,select')){let x=valid(i);if(x)return show(i,x)}s.disabled=true;try{let x=await Swal.fire({icon:'question',title:'Perbarui pengajuan ini?',text:'Pastikan data mahasiswa dan dokumen pendukung sudah benar sebelum dikirim ke Admin.',showCancelButton:true,confirmButtonText:'Ya, perbarui',cancelButtonText:'Periksa lagi',confirmButtonColor:'#c62828'});if(!x.isConfirmed)return;let r=await fetch(f.action,{method:'POST',body:new FormData(f),credentials:'same-origin',headers:{'X-Requested-With':'XMLHttpRequest','Accept':'application/json'}}),d=await r.json();if(d.success&&d.redirect)return location.assign(d.redirect);if(d.redirect&&r.status===401)return Swal.fire({icon:'error',title:'Sesi berakhir',text:d.message}).then(()=>location.assign(d.redirect));let q=/^(mhs_[a-z_]+)\[(\d+)\]$/.exec(d.field||'');show(q?f.querySelectorAll('[name="'+q[1]+'[]"]')[+q[2]]:f.elements.namedItem(d.field),d.message||'Pengajuan belum dapat diperbarui.')}catch(_){Swal.fire({icon:'error',title:'Gagal memperbarui pengajuan',text:'Koneksi atau server bermasalah. Data yang sudah diisi tetap tersedia; coba lagi.'})}finally{s.disabled=false}});
});
</script>
<?= $this->include('Pendidikan/Institusi/layout/footer') ?>
